"""
Agent A — Performer.
Executes benchmark tasks and returns scored results.
The actual task logic lives in self.task_code so the Modifier can evolve it.
"""

import time
from agents.base_agent import Agent, AgentResult


# Default task: naive bubble sort (intentionally slow — gives Modifier room to improve)
DEFAULT_TASK_CODE = '''
def run_task(data):
    arr = list(data)
    n = len(arr)
    for i in range(n):
        for j in range(0, n - i - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
    return arr
'''


class Performer(Agent):
    def __init__(self):
        super().__init__(name="Performer")
        self.task_code = DEFAULT_TASK_CODE

    def run_benchmark(self, data: list) -> AgentResult:
        """Execute the current task_code and measure performance."""
        namespace: dict = {}
        # Safe: task_code is always generated by Modifier and validated in sandbox first
        exec(self.task_code, namespace)  # noqa: S102 - controlled code path
        run_task = namespace["run_task"]

        start = time.perf_counter()
        try:
            result = run_task(data)
            duration_ms = (time.perf_counter() - start) * 1000
            return AgentResult(success=True, output=result, duration_ms=duration_ms)
        except Exception as exc:
            duration_ms = (time.perf_counter() - start) * 1000
            return AgentResult(success=False, output=None, duration_ms=duration_ms, error=str(exc))
