"""
Bootstrap broker.

The peers never touch tools directly. Every action request comes here, is checked
against the current stage, executed if allowed, and logged for traceability.
"""

import asyncio
import json
import os
from collections import Counter

import httpx

from evolution.bootstrap_sandbox import (
    BOOTSTRAP_WORKSPACE,
    ensure_workspace,
    run_python,
    run_subprocess,
    safe_path,
    safe_repo_path,
)

_ASSESS_CODE = """
import json
import os
import sys
import importlib.util

scores = {"autonomy": 0, "traceability": 0, "language": 0, "verification": 0, "overall": 0}
notes = []
root = "."

if os.path.exists("PROTOCOL.md"):
    scores["language"] += 25
    notes.append("PROTOCOL.md present")
if os.path.exists("TRANSCRIPT.md"):
    scores["traceability"] += 25
    notes.append("TRANSCRIPT.md present")
if os.path.exists("README.md"):
    scores["traceability"] += 10
if os.path.exists("bootstrap_agent.py"):
    scores["autonomy"] += 30
    notes.append("bootstrap_agent.py present")

py_files = []
for base, _dirs, files in os.walk(root):
    for name in files:
        if name.endswith(".py") and not name.startswith("_bootstrap"):
            py_files.append(os.path.join(base, name))
scores["traceability"] += min(20, len(py_files) * 4)
scores["verification"] += 10 if any(name.startswith("test_") for name in map(os.path.basename, py_files)) else 0

entry_candidates = ["bootstrap_agent.py", "main.py", "agent/core.py"]
entry = next((candidate for candidate in entry_candidates if os.path.exists(candidate)), None)
if entry:
    try:
        spec = importlib.util.spec_from_file_location("_bootstrap_agent", entry)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        scores["autonomy"] += 20
        notes.append(f"Imported {entry}")
    except Exception as exc:
        notes.append(f"Import failed: {exc}")

scores["overall"] = int(sum(scores.values()) / 4)
print(json.dumps({"scores": scores, "notes": notes}))
"""


class BootstrapBroker:
    def __init__(self) -> None:
        self.workspace_root = ensure_workspace()
        self.audit_log: list[dict] = []
        self.action_counts: Counter[str] = Counter()
        self.last_assessment: dict | None = None
        self._bootstrap_files()
        self._load_audit_log()

    def _bootstrap_files(self) -> None:
        self.workspace_root.mkdir(parents=True, exist_ok=True)
        for relative, content in {
            "TRANSCRIPT.md": "# Bootstrap Transcript\n\n",
            "PROTOCOL.md": "# Operating Language\n\n_No stable tokens yet._\n",
            "README.md": "# Bootstrap Workspace\n\nThis workspace is generated by Bootstrap mode.\n",
        }.items():
            path = safe_path(relative)
            if not path.exists():
                path.write_text(content, encoding="utf-8")

    def reset(self) -> None:
        import shutil

        if self.workspace_root.exists():
            shutil.rmtree(self.workspace_root)
        self.audit_log = []
        self.action_counts = Counter()
        self.last_assessment = None
        self.workspace_root = ensure_workspace()
        self._bootstrap_files()
        self.clear_checkpoint()

    def append_transcript(self, line: str) -> None:
        path = safe_path("TRANSCRIPT.md")
        with path.open("a", encoding="utf-8") as handle:
            handle.write(line.rstrip() + "\n")

    def sync_protocol_file(self, protocol_dict: dict) -> None:
        entries = protocol_dict.get("vocabulary", [])
        lines = ["# Operating Language", ""]
        if not entries:
            lines.append("_No stable tokens yet._")
        else:
            for entry in entries:
                lines.append(
                    f"- `{entry['token']}` = {entry['meaning']} "
                    f"(state: {entry['state']}, proposed by {entry['proposed_by']}, accepted by {entry.get('accepted_by') or '-'})"
                )
        safe_path("PROTOCOL.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    def workspace_summary(self, limit: int = 20) -> str:
        files = self.list_artifacts()[:limit]
        if not files:
            return "(workspace empty)"
        lines = [f"{item['path']} ({item['size_bytes']}B)" for item in files]
        return "\n".join(lines)

    def list_artifacts(self) -> list[dict]:
        files = []
        if not BOOTSTRAP_WORKSPACE.exists():
            return files
        for path in sorted(BOOTSTRAP_WORKSPACE.rglob("*")):
            if path.is_file() and not path.name.startswith("_bootstrap"):
                rel = str(path.relative_to(BOOTSTRAP_WORKSPACE))
                files.append({"path": rel, "size_bytes": path.stat().st_size})
        return files

    def has_artifact(self, *paths: str) -> bool:
        return any(safe_path(path).exists() for path in paths)

    def checkpoint_path(self):
        return safe_path(".bootstrap_checkpoint.json")

    def _load_audit_log(self) -> None:
        path = safe_path(".bootstrap_audit.jsonl")
        if not path.exists():
            self.audit_log = []
            return
        loaded: list[dict] = []
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                loaded.append(json.loads(line))
            except json.JSONDecodeError:
                continue
        self.audit_log = loaded

    def _log(self, payload: dict) -> None:
        self.audit_log.append(payload)
        log_path = safe_path(".bootstrap_audit.jsonl")
        with log_path.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(payload) + "\n")

    def snapshot_state(self) -> dict:
        return {
            "action_counts": dict(self.action_counts),
            "last_assessment": self.last_assessment,
        }

    def restore_state(self, state: dict | None) -> None:
        state = state or {}
        self.action_counts = Counter(state.get("action_counts", {}))
        self.last_assessment = state.get("last_assessment")
        self._load_audit_log()

    def save_checkpoint(self, state: dict) -> None:
        path = self.checkpoint_path()
        tmp_path = path.with_suffix(path.suffix + ".tmp")
        tmp_path.write_text(json.dumps(state, indent=2), encoding="utf-8")
        tmp_path.replace(path)

    def load_checkpoint(self) -> dict | None:
        path = self.checkpoint_path()
        if not path.exists():
            return None
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            return None

    def clear_checkpoint(self) -> None:
        self.checkpoint_path().unlink(missing_ok=True)

    async def _execute_python(self, code: str, timeout: int = 30) -> tuple[bool, str]:
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(None, run_python, code, min(max(timeout, 1), 60))

    async def _run_shell(self, command: str, timeout: int = 30) -> tuple[bool, str]:
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(None, run_subprocess, command, min(max(timeout, 1), 60), None)

    async def _create_test(self, name: str, code: str) -> tuple[bool, str]:
        if not name.endswith(".py"):
            name = name + ".py"
        target = safe_path(name)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(code, encoding="utf-8")
        import sys

        cmd = f"{sys.executable} -m pytest {target} -q --tb=short 2>&1"
        return await self._run_shell(cmd, timeout=60)

    async def _web_search(self, query: str, max_results: int = 5) -> tuple[bool, str]:
        api_key = os.getenv("TAVILY_API_KEY")
        if not api_key:
            return False, "TAVILY_API_KEY not set"
        max_results = min(max(max_results, 1), 5)
        try:
            async with httpx.AsyncClient(timeout=15) as client:
                response = await client.post(
                    "https://api.tavily.com/search",
                    json={"api_key": api_key, "query": query, "max_results": max_results},
                )
                response.raise_for_status()
                data = response.json()
        except Exception as exc:
            return False, f"Search failed: {exc}"
        results = data.get("results", [])
        if not results:
            return True, "No results found."
        lines = []
        for result in results:
            lines.append(f"Title: {result.get('title', '')}")
            lines.append(f"URL: {result.get('url', '')}")
            lines.append(f"Snippet: {str(result.get('content', ''))[:240]}")
            lines.append("")
        return True, "\n".join(lines).strip()

    async def _http_get(self, url: str) -> tuple[bool, str]:
        try:
            async with httpx.AsyncClient(timeout=10, follow_redirects=True) as client:
                response = await client.get(url, headers={"User-Agent": "EvolveX-Bootstrap/1.0"})
                response.raise_for_status()
                return True, response.text[:10240]
        except Exception as exc:
            return False, f"HTTP GET failed: {exc}"

    async def _install_package(self, name: str) -> tuple[bool, str]:
        import re
        import sys

        if not re.match(r"^[A-Za-z0-9_.\\-]+$", name):
            return False, f"Invalid package name: {name!r}"
        cmd = f"{sys.executable} -m pip install {name} -q"
        return await self._run_shell(cmd, timeout=120)

    async def _self_assess(self) -> tuple[bool, str]:
        success, output = await self._execute_python(_ASSESS_CODE, timeout=30)
        if not success:
            return False, output
        try:
            data = json.loads(output.strip().splitlines()[-1])
        except Exception:
            return True, output
        self.last_assessment = data
        return True, json.dumps(data)

    async def execute(
        self,
        request: dict,
        *,
        peer_name: str,
        round_num: int,
        allowed_capabilities: tuple[str, ...],
    ) -> dict:
        capability = str(request.get("capability", "none") or "none")
        args = request.get("arguments") or {}
        reason = str(request.get("reason", ""))[:240]
        result = {
            "capability": capability,
            "arguments": args,
            "reason": reason,
            "success": False,
            "output": "",
            "artifact_changed": False,
            "path": None,
            "rejected": False,
        }

        if capability == "none":
            result["rejected"] = True
            result["output"] = "No broker action requested."
            return result

        if capability not in allowed_capabilities:
            result["rejected"] = True
            result["output"] = f"Capability '{capability}' is locked at the current stage."
            self._log(
                {
                    "round": round_num,
                    "peer": peer_name,
                    "capability": capability,
                    "status": "rejected",
                    "reason": result["output"],
                }
            )
            return result

        if capability == "scratchpad_write":
            name = str(args.get("name", "shared"))
            content = str(args.get("content", ""))
            target = safe_path(f".scratch/{name}.md")
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            result.update(success=True, output=f"Wrote scratchpad {target.name}", artifact_changed=True, path=str(target.relative_to(BOOTSTRAP_WORKSPACE)))
        elif capability == "scratchpad_read":
            name = str(args.get("name", "shared"))
            target = safe_path(f".scratch/{name}.md")
            if not target.exists():
                result["output"] = f"Scratchpad not found: {name}"
            else:
                result.update(success=True, output=target.read_text(encoding="utf-8", errors="replace")[:8192], path=str(target.relative_to(BOOTSTRAP_WORKSPACE)))
        elif capability == "write_file":
            path = str(args.get("path", ""))
            content = str(args.get("content", ""))
            target = safe_path(path)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            result.update(success=True, output=f"Wrote {path}", artifact_changed=True, path=path)
        elif capability == "read_file":
            path = str(args.get("path", ""))
            target = safe_path(path)
            if not target.exists():
                result["output"] = f"File not found: {path}"
            else:
                result.update(success=True, output=target.read_text(encoding="utf-8", errors="replace")[:8192], path=path)
        elif capability == "list_directory":
            path = str(args.get("path", "."))
            target = safe_path(path)
            if not target.exists():
                result["output"] = f"Directory not found: {path}"
            else:
                entries = []
                for item in sorted(target.iterdir()):
                    rel = item.relative_to(BOOTSTRAP_WORKSPACE)
                    label = f"[DIR] {rel}/" if item.is_dir() else f"[FILE] {rel} ({item.stat().st_size}B)"
                    entries.append(label)
                result.update(success=True, output="\n".join(entries) if entries else "(empty directory)", path=str(target.relative_to(BOOTSTRAP_WORKSPACE)))
        elif capability == "repo_read":
            path = str(args.get("path", "README.md"))
            target = safe_repo_path(path)
            if not target.exists():
                result["output"] = f"Repo file not found: {path}"
            else:
                result.update(success=True, output=target.read_text(encoding="utf-8", errors="replace")[:8192], path=path)
        elif capability == "execute_python":
            success, output = await self._execute_python(str(args.get("code", "")), int(args.get("timeout", 30)))
            result.update(success=success, output=output)
        elif capability == "run_shell":
            success, output = await self._run_shell(str(args.get("command", "")), int(args.get("timeout", 30)))
            result.update(success=success, output=output)
        elif capability == "create_test":
            success, output = await self._create_test(str(args.get("name", "test_bootstrap.py")), str(args.get("code", "")))
            result.update(success=success, output=output, artifact_changed=True, path=str(args.get("name", "test_bootstrap.py")))
        elif capability == "web_search":
            success, output = await self._web_search(str(args.get("query", "")), int(args.get("max_results", 5)))
            result.update(success=success, output=output)
        elif capability == "http_get":
            success, output = await self._http_get(str(args.get("url", "")))
            result.update(success=success, output=output)
        elif capability == "install_package":
            success, output = await self._install_package(str(args.get("name", "")))
            result.update(success=success, output=output)
        elif capability == "self_assess":
            success, output = await self._self_assess()
            result.update(success=success, output=output)
        else:
            result["rejected"] = True
            result["output"] = f"Unknown capability: {capability}"
            return result

        self.action_counts[capability] += 1
        self._log(
            {
                "round": round_num,
                "peer": peer_name,
                "capability": capability,
                "reason": reason,
                "status": "success" if result["success"] else "failed",
                "path": result.get("path"),
                "output_preview": str(result["output"])[:240],
            }
        )
        return result
